<a href="https://colab.research.google.com/github/riyajindal2k/Mini-Project/blob/main/Minor_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# libraries required
import os
import matplotlib.pyplot as plt
import numpy as np
import cv2
from skimage.io import imread
from skimage.transform import resize

In [3]:
target = []
images = []
flat_data = []

DATADIR = '/content/drive/MyDrive/images'
CATEGORIES = ['earphones','laptop','speaker']
for category in CATEGORIES:
  class_num = CATEGORIES.index(category)        # label encoding the values
  path = os.path.join(DATADIR,category)         # Create path to use all the images, e.g - /content/images/earphones
  print(path)
  
  for img in os.listdir(path):
    #print(os.path.join(path,img))
    img_array = cv2.imread(os.path.join(path,img))
    #print(img_array.shape)
    #plt.imshow(img_array)
    img_resized = resize(img_array,(150,150,3))                         # Normalizes the value 0 to 1
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)



/content/drive/MyDrive/images/earphones
/content/drive/MyDrive/images/laptop
/content/drive/MyDrive/images/speaker


In [4]:
# Split data into Training and Testing

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(flat_data,target,test_size=0.3,random_state=109)

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = [
                  {'C':[1,10,100,1000],'kernel':['linear']},
                  {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},
]

svc = SVC(probability=True)
clf = GridSearchCV(svc, param_grid)
clf.fit(x_train, y_train)


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [5]:
y_pred = clf.predict(x_test)
print(y_pred)

[1 0 1 2 2 1 0 1 2 0 2 0 2 1 2 2 2 1 0 2 1 2 1 0 0 0 1]


In [6]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))

0.7037037037037037
[[8 0 0]
 [0 6 3]
 [0 5 5]]
